# O Módulo externo `numpy` 🥰🥰🥰🥰🥰🥰

O [numpy](https://numpy.org/) não é um pacote nativo do Python. Aqui no Colab nós podemos usá-lo sem necessidade de instalação. Mas em outra IDE, é necessário instalar! Ele deve ser instalado separadamente (a instalação é muito fácil). O módulo apresenta objetos de matriz que são semelhantes a listas, mas podem ser manipulados por várias funções contidas no módulo. 

## Instalando o Numpy:

In [ ]:
!pip install numpy

## Alguns recursos do numpy

O conjunto completo de funções do numpy é muito longo para ser impresso em sua totalidade. A lista a seguir é limitada apenas a algumas funções tipicamente usadas.

<font color='purple'>[’complex’, ’float’, ’abs’, ’append’, arccos’, ’arccosh’, ’arcsin’, ’arcsinh’, ’arctan’, ’arctan2’, ’arctanh’, ’argmax’, ’argmin’, ’cos’, ’cosh’, ’diag’, ’diagonal’, ’dot’, ’e’, ’exp’, ’floor’, ’identity’, ’inner, ’inv’, ’log’, ’log10’, ’max’, ’min’, ’ones’, ’outer’, ’pi’, ’prod’ ’sin’, ’sinh’, ’size’, ’solve’, ’sqrt’, ’sum’, ’tan’, ’tanh’, ’trace’, ’transpose’, ’vectorize’,’zeros’]</font>

### Criando Arrays Numpy:

In [ ]:
import numpy as np

Criando um array unidimensional de valores inteiros:




In [ ]:
a = np.array([1, 2, 3], dtype= int)
print(a)

[1 2 3]


Criando um array bidimensional de valores reais (ponto flutuante):


In [ ]:
b = np.array([[2.0,-1.0],[-1.0, 3.0]], dtype = float)
print(b)

[[ 2. -1.]
 [-1.  3.]]


Se eu não especificar o tipo numérico de dados, os valores tão representação de ponto flutuante por padrão:

In [ ]:
c = np.array([[2.0,-1.0],[-1.0, 3.0]])
print(c)

[[ 2. -1.]
 [-1.  3.]]


Outras maneiras de se criar arrays numpy:

In [ ]:
print(np.arange(2,10,2))
print(np.zeros(3))
print(np.ones((3,3), dtype=int))
print(np.identity(3))

[2 4 6 8]
[0. 0. 0.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Acessando a alterando elementos dos arrays:

In [ ]:
a = np.zeros((3,3), dtype = int)
a[0] = [2,3,2]
a[1, 1] = 5
a[2, 0:2] = [8,-3]
print(a)

[[ 2  3  2]
 [ 0  5  0]
 [ 8 -3  0]]


### Convertendo arrays numpy em listas: 

In [ ]:
list_a = a.tolist()
print(type(list_a))


<class 'list'>


### Operações sobre arrays:

<font color='red'>Dividindo todos os elementos de uma lista por 16: Sem usar os recurso do numpy: </font> 🤡



In [ ]:
a = [0.0, 4.0, 9.0, 16.0]
for i in range(len(a)):
  a[i] = a[i]/16.0

print(a)

[0.0, 0.25, 0.5625, 1.0]


Usando os recusros do numpy para solucionar o mesmo problema: 👊

In [ ]:
a = np.array([0.0, 4.0, 9.0, 16.0])
print(a/16.0)

[0.     0.25   0.5625 1.    ]


Outras operações semelhantes: 

In [ ]:
a = np.array([0.0, 4.0, 9.0, 16.0])
print(a/16.0)
print(a - 4.0)
print(a*2)
print(np.sqrt(a))
print(np.sin(a))

[0.     0.25   0.5625 1.    ]
[-4.  0.  5. 12.]
[ 0.  8. 18. 32.]
[0. 2. 3. 4.]
[ 0.         -0.7568025   0.41211849 -0.28790332]


<font color='red'>Obtendo os alementos da diagonal pricipal a partir de uma lista:</font> 🤡

In [ ]:
lista_a = [[4,-2,1],[-2,4,-2],[1,-2,3]]
diagonal = []
for linha in range(3):
  for coluna in range(3):
    if linha == coluna:
      diagonal.append(lista_a[linha][coluna])

print(diagonal)

[4, 4, 3]


Mesma operação utilizando array numpy: 👊

In [ ]:
a = np.asarray(lista_a)
print(np.diagonal(a))

[4 4 3]


In [ ]:
# traço de uma matriz: soma dos elementos da diagonal principal
print(np.trace(a))
# indice do menor elemento de cada linha
print(np.argmin(a,axis=0))
# indice do maior elemento de cada coluna
print(np.argmax(a,axis=1))

11
[1 0 1]
[0 1 2]


In [ ]:
x = np.array([7,3]) 
y = np.array([2,1]) 
A = np.array([[1,2],[3,2]]) 
B = np.array([[1,1],[2,2]])

Produto escalar entre arrays:

In [ ]:
# Dot product (Produto escalar)
print("dot(x,y) =\n",np.dot(x,y)) # {x}.{y}
print("dot(A,x) =\n",np.dot(A,x)) # [A]{x}
print("dot(A,B) =\n",np.dot(A,B)) # [A][B]

dot(x,y) =
 17
dot(A,x) =
 [13 27]
dot(A,B) =
 [[5 5]
 [7 7]]


In [ ]:
# Inner product (produto interno)
print("inner(x,y) =\n",np.inner(x,y)) # {x}.{y} 
print("inner(A,x) =\n",np.inner(A,x)) # [A]{x} 
print("inner(A,B) =\n",np.inner(A,B)) # [A][B_transpose]

inner(x,y) =
 17
inner(A,x) =
 [13 27]
inner(A,B) =
 [[ 3  6]
 [ 5 10]]


### Módulo de Álgebra Linear </font>(Muito importante para o cálculo numérico)</font>

In [ ]:
from numpy import linalg 

In [ ]:
A = np.array([[ 4.0,-2.0, 1.0], [-2.0, 4.0,-2.0], [ 1.0,-2.0, 3.0]])
b = np.array([1.0, 4.0, 2.0])

# solução de Ax = b
print(linalg.solve(A,b))

# cálculo ma matriz inversa
print(linalg.inv(A))

[1.  2.5 2. ]
[[0.33333333 0.16666667 0.        ]
 [0.16666667 0.45833333 0.25      ]
 [0.         0.25       0.5       ]]
